name: Auto Tag and GitHub Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Tag and create release
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GH_PAT }}
